server:
  port:  8093
  address: 192.168.146.1
spring:
  application:
    name: fsh-house
eureka:
  client:
    service-url:
      #defaultZone:  http://localhost:8762/eureka/
      #defaultZone:  http://yunhui-eureka:123456@localhost:8762/eureka/
      ##服务方注册到集群 的eureka注册中心上
#      defaultZone:  http://yunhui-eureka:123456@master:8761/eureka/,http://yunhui-eureka03:123456@slaveone:8763/eureka/
      defaultZone:  http://yunhui-eureka:123456@10.1.252.2:8761/eureka/,http://yunhui-eureka03:123456@10.1.252.2:8763/eureka/

  instance:
    ###自定义eureka的ip显示
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    #自定义实例跳转链接
    status-page-url: http://cxytiandi.com/
