server:
  port:  8091
spring:
  application:
    name: fsh-house
eureka:
  client:
    service-url:
      #defaultZone:  http://localhost:8762/eureka/
      defaultZone:  http://yunhui-eureka:123456@localhost:8762/eureka/
#security:
#  basic:
#    enabled: false
