host: localhost #localhost  #10.1.252.2

server:
  port: 8761
spring:
  application:
    name: yunhui-eureka
eureka:
  instance:
    hostname: ${host}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://yunhui-eureka03:1234567@slaveone:8763/eureka/
  server:
    enable-self-preservation: false  # 关闭自我保护
    eviction-interval-timer-in-ms: 5000  #默认60000毫秒   ##清理间隔

#####搭建集群的配
security:
  basic:
    enabled: true #开启认证
  user:
    name: yunhui-eureka
    password: 123456

