host: 10.1.252.2

server:
  port: 8763
spring:
  application:
    name: yunhui-eureka
eureka:
  instance:
    hostname: ${host}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://yunhui-eureka:123456@master:8761/eureka/
  server:
    enable-self-preservation: false  # 关闭自我保护


security:
  basic:
    enabled: true #开启认证
  user:
    name: yunhui-eureka03
    password: 123456

#  name: yunhui-eureka03 #用户名
#  password: 123456    #密码
#####搭建集群的配
