server:
  port: 8082
spring:
  application:
    name: fsh-substitution

eureka:
  client:
    service-url:
      defaultZone:  http://yunhui-eureka:123456@master:8761/eureka/,http://yunhui-eureka03:123456@slaveone:8763/eureka/


yun:
  url8081:
    host: http://localhost:8091
    requeset:
      housedata: ${yun.url8081.host}/house/data?name=